name: Deployment Prep
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  config:
    if: github.repository == 'ngeorger/github-readme-stats'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4.1.1
      - name: Deployment Prep
        run: python ./.github/workflows/deploy-prep.py
      - uses: stefanzweifel/git-auto-commit-action@v5 # v5.0.0
        with:
          branch: vercel
          create_branch: true
          push_options: "--force"
